__include__: [
  '../dataset/dronesite.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

tuning: ./ckpts/rtdetrv2_r50vd_6x_coco_ema.pth

output_dir: ./output/aug_e36

epoches: 36

train_dataloader: 
  total_batch_size: 8

val_dataloader:
  total_batch_size: 16

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

